channels:
- anaconda
- pytorch
- conda-forge
- menpo
dependencies:
- python=3.11.13
- pip>=21.0
- pytorch>=2.1.0
- torchvision
- torchaudio
- cudatoolkit
- scikit-image
- opencv
- cupy
- pip:
  - matplotlib>=3.3
  - psutil>=5.8
  - tqdm>=4.57.0
  - pandas
  - scipy
  - numpy>=1.20.0
  - tensorboard
  - future
  - kornia
  - hydra-core==1.3.2
  - wget==3.2
  - seaborn
  - easydict
  - torchpq
  - git+https://github.com/lucasb-eyer/pydensecrf.git
  - setuptools>=59.5.0
  - pyDeprecate>=0.3.1
  - pytorch-lightning==2.5.2
  - torchmetrics==1.7.4
name: stego-updated
